# Generated by Django 4.1.7 on 2023-03-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="uploaded_at",
        ),
    ]
